[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = [
  "npm install -g corepack@latest",
  "corepack enable",
  "corepack prepare pnpm@9.15.9 --activate",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"